use lalrpop_util::ErrorRecovery;
use lalrpop_util::ParseError;
use ordered_float::OrderedFloat;

use crate::aiplan4rust::frontend::ParserInternalError;
use crate::aiplan4rust::lang::ArithmeticOp;
use crate::aiplan4rust::lang::AssignOp;
use crate::aiplan4rust::lang::BinaryComp;
use crate::aiplan4rust::lang::Optimization;
use crate::aiplan4rust::lang::Requirement;
use crate::aiplan4rust::syntax::lexer::LexicalError;
use crate::aiplan4rust::syntax::lexer::Token;
use crate::aiplan4rust::syntax::ast::AstKind;
use crate::aiplan4rust::syntax::ast::AstContent;
use crate::aiplan4rust::syntax::ParseContext;
use crate::aiplan4rust::tree::NodeId;

grammar<'ctx>(context: &'ctx mut ParseContext);

extern {

  type Location = usize;
  type Error = LexicalError;

    enum Token {

       // Identifiers
       "id" => Token::ID(<String>),
       //"?id" => Token::VarID(<String>),
       "number" => Token::Number(<f64>),

        // Keywords
        "define" => Token::Define,
        "domain" => Token::Domain,
        "problem" => Token::Problem,
        ":requirements" => Token::Requirements,
        ":types" => Token::Types,
        "either" => Token::Either,
        ":constants" => Token::Constants,
        ":predicates" => Token::Predicates,
        ":functions" => Token::Functions,
        ":action" => Token::Action,
        ":parameters" => Token::Parameters,
        ":precondition" => Token::Precondition,
        ":effect" => Token::Effect,
        ":derived" => Token::Derived,
        ":durative-action" => Token::DurativeAction,
        ":duration" => Token::Duration,
        ":condition" => Token::Condition,
        ":domain" => Token::DomainDef,
        ":objects" => Token::Objects,
        ":init" => Token::Init,
        ":goal" => Token::Goal,
        ":metric" => Token::Metric,

        // Deprecated since PDDL2.1
        ":length" => Token::Length,
        ":serial" => Token::Serial,
        ":parallel" => Token::Parallel,

        // Expressions
        "preference" => Token::Preference,
        "and" => Token::And,
        "or" => Token::Or,
        "not" => Token::Not,
        "imply" => Token::Imply,
        "forall" => Token::Forall,
        "exists" => Token::Exists,
        "when" => Token::When,

        // Requirements
        ":strips" => Token::Strips,
        ":typing" => Token::Typing,
        ":negative-preconditions" => Token::NegativePreconditions,
        ":disjunctive-preconditions" => Token::DisjunctivePreconditions,
        ":equality" => Token::Equality,
        ":existential-preconditions" => Token::ExistentialPreconditions,
        ":universal-preconditions" => Token::UniversalPreconditions,
        ":quantified-preconditions" => Token::QuantifiedPreconditions,
        ":conditional-effects" => Token::ConditionalEffects,
        ":fluents" => Token::Fluents,
        ":numeric-fluents" => Token::NumericFluents,
        ":object-fluents" => Token::ObjectFluents,
        ":adl" => Token::Adl,
        ":durative-actions" => Token::DurativeActions,
        ":duration-inequalities" => Token::DurationInequalities,
        ":continuous-effects" => Token::ContinuousEffects,
        ":derived-predicates" => Token::DerivedPredicates,
        ":timed-initial-literals" => Token::TimedInitialLiterals,
        ":preferences" => Token::Preferences,
        ":constraints" => Token::Constraints,
        ":action-costs" => Token::ActionCosts,

        // Time
        "at start" => Token::AtStart,
        "at end" => Token::AtEnd,
        "over all" => Token::OverAll,

        // Constraints
        "always" => Token::Always,
        "sometime" => Token::Sometime,
        "within" => Token::Within,
        "at-most-once" => Token::AtMostOnce,
        "sometime-after" => Token::SometimeAfter,
        "sometime-before" => Token::SometimeBefore,
        "always-within" => Token::AlwaysWithin,
        "hold-during" => Token::HoldDuring,
        "hold-after" => Token::HoldAfter,

        // Separators
        "(" => Token::LParen,
        ")" => Token::RParen,

        // Arithmetic operators
        "-" => Token::Sub,
        "+" => Token::Add,
        "/" => Token::Div,
        "*" => Token::Mul,

        // Comparison operators
        ">" => Token::Greater,
        "<" => Token::Less,
        "=" => Token::Equal,
        ">=" => Token::GreaterEq,
        "<=" => Token::LessEq,

        // Assign operators
        "assign" => Token::Assign,
        "scale-up" => Token::ScaleUp,
        "scale-down" => Token::ScaleDown,
        "increase" => Token::Increase,
        "decrease" => Token::Decrease,

        // Opitimization
        "minimize" => Token::Minimize,
        "maximize" => Token::Maximize,

        // Special
        "object_type" => Token::ObjectType,
        "number_type" => Token::NumberType,
        "undefined" => Token::Undefined,
        "?duration" => Token::DurationVariable,
        "#t" => Token::SharpT,
        "total-time" => Token::TotalTime,
        "is-violated" => Token::IsViolated,

        // Error
        "error" => Token::Error(<String>),

        // HDDL
        ":hierarchy" => Token::Hierarchy,
        ":method-preconditions" => Token::MethodPreconditions,
        ":task" => Token::Task,
        ":tasks" => Token::Tasks,
        ":method" => Token::Method,
        ":ordered-subtasks" => Token::OrderedSubtasks,
        ":ordered-tasks" => Token::OrderedTasks,
        ":subtasks" => Token::Subtasks,
        ":ordering" => Token::Ordering,
        ":order" => Token::Order,
        ":htn" => Token::Htn,
    }
}

pub Name : Result<AstContent, ()> = {
    <start:@L>  <name:"id"> <end:@R> => {
        if name.starts_with("?") {
            let parse_error = ParseError::UnrecognizedToken {
                token : (start, Token::ID(name), end),
                expected : vec!["\"id\"".to_string()],
            };
           let error_recovery = ErrorRecovery { error: parse_error, dropped_tokens: Vec::new() };
           context.push(error_recovery);
           Err(())
        } else {
            Ok(AstContent::Ident(context.intern(name.to_string())))
        }
    },
    <start:@L> <error:!> <end:@R>  => {
        context.push(error);
        Err(())
    },
    // Addition to allow the use of special symbols as ordinary symbols. The verification will be performed during
    // semantics analysis
    <start:@L> <name:"object_type"> <end:@R> => Ok(AstContent::Ident(context.intern(name.to_string()))),
    <start:@L> <name:"number_type"> <end:@R> => Ok(AstContent::Ident(context.intern(name.to_string()))),
    <start:@L> <name:"total-time"> <end:@R> => Ok(AstContent::Ident(context.intern(name.to_string()))),
}

pub VarName : Result<AstContent, ()> = {
    <start:@L>  <name:"id"> <end:@R> => {
        if !name.starts_with("?") {
            let parse_error = ParseError::UnrecognizedToken {
                token : (start, Token::ID(name), end),
                expected : vec!["\"?id\"".to_string()],
            };
           let error_recovery = ErrorRecovery { error: parse_error, dropped_tokens: Vec::new() };
           context.push(error_recovery);
           Err(())
        } else {
            Ok(AstContent::Ident(context.intern(name.to_string())))
        }
    },
    <start:@L> <error:!> <end:@R>  => {
        context.push(error);
        Err(())
    },
}

pub Constant: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::Constant, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    }
}

pub Variable: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:VarName> <end:@R> => {
        match name {
            Ok(name) => context.new_node(AstKind::Variable, name, Vec::new(), start, end, None),
            Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
        }
    },
    <var:DurationVariable> => var,
}

pub FunctionSymbol: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => {
        match name {
            Ok(name) => context.new_node(AstKind::FunctionSymbol, name, Vec::new(), start, end, None),
            Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
        }
    },
}

pub Number: Result<NodeId, ParserInternalError> = {
    <start:@L> <value:"number"> <end:@R> => {
        context.new_node(AstKind::Number, AstContent::Float(OrderedFloat(value)), Vec::new(), start, end, None)
    },
}

pub DomainName: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::DomainName, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub ProblemName: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::ProblemName, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub PrimitiveType: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::PrimitiveType, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub Predicate: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::Predicate, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub ActionSymbol: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::ActionSymbol, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub DASymbol: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::DASymbol, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub PrefName: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::PrefName, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    },
}

pub Requirement: Result<NodeId, ParserInternalError> = {
    <start:@L> ":strips" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Strips), Vec::new(), start, end, None),
    <start:@L> ":typing" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Typing), Vec::new(), start, end, None),
    <start:@L> ":equality" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Equality), Vec::new(), start, end, None),
    <start:@L> ":negative-preconditions" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::NegativePreconditions), Vec::new(), start, end, None),
    <start:@L> ":disjunctive-preconditions" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::DisjunctivePreconditions), Vec::new(), start, end, None),
    <start:@L> ":existential-preconditions" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::ExistentialPreconditions), Vec::new(), start, end, None),
    <start:@L> ":universal-preconditions" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::UniversalPreconditions), Vec::new(), start, end, None),
    <start:@L> ":quantified-preconditions" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::QuantifiedPreconditions), Vec::new(), start, end, None),
    <start:@L> ":conditional-effects" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::ConditionalEffects), Vec::new(), start, end, None),
    <start:@L> ":fluents" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Fluents), Vec::new(), start, end, None),
    <start:@L> ":numeric-fluents" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::NumericFluents), Vec::new(), start, end, None),
    <start:@L> ":object-fluents" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::ObjectFluents), Vec::new(), start, end, None),
    <start:@L> ":adl" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Adl), Vec::new(), start, end, None),
    <start:@L> ":durative-actions" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::DurativeActions), Vec::new(), start, end, None),
    <start:@L> ":duration-inequalities" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::DurationInequalities), Vec::new(), start, end, None),
    <start:@L> ":continuous-effects" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::ContinuousEffects), Vec::new(), start, end, None),
    <start:@L> ":derived-predicates" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::DerivedPredicates), Vec::new(), start, end, None),
    <start:@L> ":timed-initial-literals" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::TimedInitialLiterals), Vec::new(), start, end, None),
    <start:@L> ":preferences" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Preferences), Vec::new(), start, end, None),
    <start:@L> ":constraints" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Constraints), Vec::new(), start, end, None),
    <start:@L> ":action-costs" <end:@R> => context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::ActionCosts), Vec::new(), start, end, None),
    <start:@L> <error:!> <end:@R> => {
        context.push(error);
        context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None)
    },
}

pub RequireDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":requirements" <requirements:Requirement*> ")" <end:@R> => {
        let requirements = requirements.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::RequireDef, AstContent::None, requirements, start, end, None)
    }
}

pub Type: Result<NodeId, ParserInternalError> = {
    <start:@L> <ty:PrimitiveType> <end:@R> => {
        context.new_node(AstKind::Type, AstContent::None, vec![ty?], start, end, None)
    },
    <start:@L> "(" "either" <types:PrimitiveType+> ")" <end:@R> => {
        let types = types.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::Type, AstContent::None, types, start, end, None)
    }
}

TypedList<T>: Result<NodeId, ParserInternalError> = {
    <start:@L> <elements:T*> <end:@R> => {
        let elements = elements.into_iter().collect::<Result<Vec<_>, _>>()?;
        let typed_item_elt = context.new_node(AstKind::TypedItemElements, AstContent::None, elements, start, end, None);
        let typed_item = context.new_node(AstKind::TypedItem, AstContent::None, vec![typed_item_elt?], start, end, None);
        context.new_node(AstKind::TypedList, AstContent::None, vec![typed_item?], start, end, None)
    },
    <start:@L> <elements:T+> <end_elements:@R> "-" <ty:Type> <end_typed_item:@R> <mut next:TypedList<T>> <end:@R> => {
        let elements = elements.into_iter().collect::<Result<Vec<_>, _>>()?;
        let typed_item_elt = context.new_node(AstKind::TypedItemElements, AstContent::None, elements, start, end_elements, None);
        let typed_item = context.new_node(AstKind::TypedItem, AstContent::None, vec![typed_item_elt?, ty?], start, end_typed_item, None);
        let mut typed_list = context.new_node(AstKind::TypedList, AstContent::None, vec![typed_item?], start, end, None);
        context.merge_typed_list(typed_list?, next?)
    }
}

pub TypesDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":types" <types:TypedList<PrimitiveType>> ")" <end:@R> => {
        context.new_node(AstKind::TypesDef, AstContent::None, vec![types?], start, end, None)
    }
}

pub ConstantsDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":constants" <constants:TypedList<Constant>> ")" <end:@R> => {
        context.new_node(AstKind::ConstantsDef, AstContent::None, vec![constants?], start, end, None)
    }
}

pub PredicatesDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":predicates" <predicates:AtomicFormulaSkeleton+> ")" <end:@R> => {
        let predicates = predicates.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::PredicatesDef, AstContent::None, predicates, start, end, None)
    }
}

pub AtomicFormulaSkeleton: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <predicate:Predicate> <arguments:TypedList<Variable>> ")" <end:@R> => {
        context.new_node(AstKind::AtomicFormulaSkeleton, AstContent::None, vec![predicate?, arguments?], start, end, None)
    }
}

pub FunctionsDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":functions" <functions:TypedList<AtomicFunctionSkeleton>> ")" <end:@R> => {
        context.new_node(AstKind::FunctionsDef, AstContent::None, vec![functions?], start, end, None)
    }
}

pub AtomicFunctionSkeleton:  Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <functor:FunctionSymbol> <arguments:TypedList<Variable>> ")" <end:@R> => {
        context.new_node(AstKind::AtomicFunctionSkeleton, AstContent::None, vec![functor?, arguments?], start, end, None)
    }
}

pub StructureDef: Result<NodeId, ParserInternalError> = {
    <action:ActionDef> => action,
    <derived:DerivedDef> => derived,
    <durative_action:DurativeActionDef> => durative_action,
}

pub ActionDef: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" ":action"
            <name:ActionSymbol>
            <parameters:ParameterDef>
            <body:ActionDefBody>
        ")"
    <end:@R> => {
        context.new_node(AstKind::ActionDef, AstContent::None, vec![name?, parameters?, body?], start, end, None)
    }
}

pub ParameterDef: Result<NodeId, ParserInternalError> = {
    <start:@L>
       ":parameters" "(" <parameters:TypedList<Variable>> ")"
    <end:@R> => {
        context.new_node(AstKind::ParametersDef, AstContent::None, vec![parameters?], start, end, None)
    }
}

pub ActionDefBody: Result<NodeId, ParserInternalError> = {
    <start:@L> <precondition:PreconditionDef?> <effect:EffectDef?> <end:@R> => {
        let mut children = Vec::new();
        if let Some(pre) = precondition {
            children.push(pre?);
        }
        if let Some(eff) = effect {
            children.push(eff?);
        }
        context.new_node(AstKind::ActionDefBody, AstContent::None, children, start, end, None)
    }
}

pub PreconditionDef: Result<NodeId, ParserInternalError> = {
    <start:@L> ":precondition" <precondition:EmptyOr<PreGD>> <end:@R> => {
        context.new_node(AstKind::PreconditionDef, AstContent::None, vec![precondition?], start, end, None)
    }
}

pub EffectDef: Result<NodeId, ParserInternalError> = {
    <start:@L> ":effect" <effect:EmptyAnd<Effect>> <end:@R> => {
        context.new_node(AstKind::EffectDef, AstContent::None, vec![effect?], start, end, None)
    }
}

EmptyOr<T>: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ")" <end:@R> => {
        context.new_node(AstKind::Or, AstContent::None, Vec::new(), start, end, None)
    },
    <start:@L> <element:T> <end:@R> => element,
}

EmptyAnd<T>: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ")" <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, Vec::new(), start, end, None)
    },
    <start:@L> <element:T> <end:@R> => element,
}

pub PreGD: Result<NodeId, ParserInternalError> = {
    <start:@L> <pref_gd:PrefGD> <end:@R> => pref_gd,
    <atom:AtomicFormula<Term>> => atom,
    <start:@L> "(" "and" <pre_gd:PreGD*> ")" <end:@R> => {
        let pre_gd = pre_gd.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, pre_gd, start, end, None)
    },
    <start:@L> "(" "or" <gd:GD*> ")" <end:@R> => {
        let gd = gd.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::Or, AstContent::None, gd, start, end, None)
    },
    <start:@L> "(" "not" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::Not, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "imply" <antecedent:GD> <consequence:GD> ")" <end:@R> => {
        context.new_node(AstKind::Imply, AstContent::None, vec![antecedent?, consequence?], start, end, None)
    },
    <start:@L>
        "(" "exists"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <gd:GD>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Exists, AstContent::None, vec![variables?, gd?], start, end, None)
    },
    <start:@L>
        "(" "forall"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <pre_gd:PreGD>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Forall, AstContent::None, vec![variables?, pre_gd?], start, end, None)
    },
    <fcomp:FComp> => fcomp,
}

pub PrefGD: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "preference" <pref_name:PrefName?> <gd:GD> ")" <end:@R> => {
        let mut children = Vec::new();
        if let Some(pref_name) = pref_name {
            children.push(pref_name?);
        }
        children.push(gd?);
        context.new_node(AstKind::Preference, AstContent::None, children, start, end, None)
    },
}

pub GD: Result<NodeId, ParserInternalError> = {
    <atom:AtomicFormula<Term>> => atom,
    <start:@L> "(" "and" <gd:GD*> ")" <end:@R> => {
        let gd = gd.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, gd, start, end, None)
    },
    <start:@L> "(" "or" <gd:GD*> ")" <end:@R> => {
        let gd = gd.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::Or, AstContent::None, gd, start, end, None)
    },
    <start:@L> "(" "not" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::Not, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "imply" <antecedent:GD> <consequence:GD> ")" <end:@R> => {
        context.new_node(AstKind::Imply, AstContent::None, vec![antecedent?, consequence?], start, end, None)
    },
    <start:@L>
        "(" "exists"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <gd:GD>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Exists, AstContent::None, vec![variables?, gd?], start, end, None)
    },
    <start:@L>
        "(" "forall"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <gd:GD>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Forall, AstContent::None, vec![variables?, gd?], start, end, None)
    },
    <fcomp:FComp> => fcomp,
}

pub Effect: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "and" <effects:CEffect*> ")" <end:@R> => {
        let effects = effects.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, effects, start, end, None)
    },
    <effect:CEffect> => effect,
}

pub CEffect: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" "forall"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <effect:Effect>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Forall, AstContent::None, vec![variables?, effect?], start, end, None)
    },
    <start:@L> "(" "when" <gd:GD> <effect:CondEffect> ")" <end:@R> => {
        context.new_node(AstKind::When, AstContent::None, vec![gd?, effect?], start, end, None)
    },
    <effect:PEffect> => effect,
}

pub PEffect: Result<NodeId, ParserInternalError> = {
    <literal:Literal<Term>> => literal,
    <start:@L> "(" <op:AssignOp> <fhead:FHead> <fexp:_FExp> ")" <end:@R> => {
        context.new_node(AstKind::Assign, op, vec![fhead?, fexp?], start, end, None)
    },
}

pub CondEffect: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "and" <effects:PEffect*> ")" <end:@R> => {
        let effects = effects.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, effects, start, end, None)
    },
    <effect:PEffect> => effect,
}

pub Term: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:"id"> <end:@R> => {
        if !name.starts_with("?") {
            context.new_node(AstKind::Constant, AstContent::Ident(context.intern(name)), Vec::new(), start, end, None)
        } else {
            context.new_node(AstKind::Variable, AstContent::Ident(context.intern(name)), Vec::new(), start, end, None)
        }
    },
    <duration:DurationVariable> => duration,
    <function:FunctionTerm> => function,
}

pub FunctionTerm: Result<NodeId, ParserInternalError> = {
    <function_term:_FunctionTerm<Term>> => function_term,
}

_FunctionTerm<T>: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <function_symbol:FunctionSymbol> <arguments:T*> ")" <end:@R> => {
        let arguments = arguments.into_iter().collect::<Result<Vec<_>, _>>()?;
        let mut children = Vec::new();
        children.push(function_symbol?);
        children.extend(arguments);
        context.new_node(AstKind::FunctionTerm, AstContent::None, children, start, end, None)
    }
}

pub FComp: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <comparator:BinaryComp> <arg1:_FExp> <arg2:_FExp> ")" <end:@R> => {
        context.new_node(AstKind::FComp, comparator, vec![arg1?, arg2?], start, end, None)
    }
}

pub BinaryComp : AstContent = {
    ">" =>AstContent::BinaryComp(BinaryComp::Greater),
    "<" =>AstContent::BinaryComp(BinaryComp::Less),
    "=" =>AstContent::BinaryComp(BinaryComp::Equal),
    ">=" =>AstContent::BinaryComp(BinaryComp::GreaterEq),
    "<=" =>AstContent::BinaryComp(BinaryComp::LessEq),
}

pub AssignOp : AstContent = {
    "assign" =>AstContent::AssignOp(AssignOp::Assign),
    "scale-up" =>AstContent::AssignOp(AssignOp::ScaleUp),
    "scale-down" =>AstContent::AssignOp(AssignOp::ScaleDown),
    "increase" =>AstContent::AssignOp(AssignOp::Increase),
    "decrease" =>AstContent::AssignOp(AssignOp::Decrease),
}

pub ArithmeticOp : AstContent = {
    "-" =>AstContent::ArithmeticOp(ArithmeticOp::Sub),
    "+" =>AstContent::ArithmeticOp(ArithmeticOp::Add),
    "/" =>AstContent::ArithmeticOp(ArithmeticOp::Div),
    "*" =>AstContent::ArithmeticOp(ArithmeticOp::Mul),
}

Literal<T>: Result<NodeId, ParserInternalError> = {
    <atom:AtomicFormula<T>> => atom,
    <start:@L> "(" "not" <atom:AtomicFormula<T>> ")" <end:@R> => {
        context.new_node(AstKind::Not, AstContent::None, vec![atom?], start, end, None)
    }
}

AtomicFormula<T>: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <predicate:Predicate> <terms:T*> ")" <end:@R> => {
        let terms = terms.into_iter().collect::<Result<Vec<_>, _>>()?;
        let mut children = Vec::new();
        children.push(predicate?);
        children.extend(terms);
        context.new_node(AstKind::AtomicFormula, AstContent::None, children, start, end, None)
    }
}

_FExp: Result<NodeId, ParserInternalError> = {
    <term:Term> => term,
    <number:Number> => number,
    <start:@L> "(" "-" <arg1:_FExp> <arg2:_FExp?> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        if let Some(arg2) = arg2 {
            children.push(arg2?);
        }
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Sub), children, start, end, None)
    },
    <start:@L> "(" "/" <arg1:_FExp> <arg2:_FExp> ")" <end:@R> => {
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Div), vec![arg1?, arg2?], start, end, None)
    },
    <start:@L> "(" "+" <arg1:_FExp> <next_args:_FExp+> ")" <end:@R> => {
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        let mut children = Vec::new();
        children.push(arg1?);
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Add), children, start, end, None)
    },
    <start:@L> "(" "*" <arg1:_FExp> <next_args:_FExp+> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Mul), children, start, end, None)
    },
}

pub FExp: Result<NodeId, ParserInternalError> = {
    <number:Number> => number,
    <start:@L> "(" "-" <arg1:FExp> <arg2:FExp?> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        if let Some(arg2) = arg2 {
            children.push(arg2?);
        }
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Sub), children, start, end, None)
    },
    <start:@L> "(" "/" <arg1:FExp> <arg2:FExp> ")" <end:@R> => {
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Div), vec![arg1?, arg2?], start, end, None)
    },
    <start:@L> "(" "+" <arg1:FExp> <next_args:FExp+> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Add), children, start, end, None)
    },
    <start:@L> "(" "*" <arg1:FExp> <next_args:FExp+> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Mul), children, start, end, None)
    },
    <fhead:FHead> => fhead,
}

pub FExpDA: Result<NodeId, ParserInternalError> = {
    <number:Number> => number,
    <start:@L> "(" "-" <arg1:FExpDA> <arg2:FExpDA?> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        if let Some(arg2) = arg2 {
            children.push(arg2?);
        }
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Sub), children, start, end, None)
    },
    <start:@L> "(" "/" <arg1:FExpDA> <arg2:FExpDA> ")" <end:@R> => {
        context.new_node(
            AstKind::Operation,
            AstContent::ArithmeticOp(ArithmeticOp::Div),
            vec![arg1?, arg2?],
            start,
            end,
            None,
        )
    },
    <start:@L> "(" "+" <arg1:FExpDA> <next_args:FExpDA+> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Add), children, start, end, None)
    },
    <start:@L> "(" "*" <arg1:FExpDA> <next_args:FExpDA+> ")" <end:@R> => {
        let mut children = Vec::new();
        children.push(arg1?);
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Mul), children, start, end, None)
    },
    <fhead:FHead> => fhead, // Add to accept the good syntax
    //<fexp:FExp> => fexp, // Remove for conflict
    <duration:DurationVariable> => duration,
}

pub FHead: Result<NodeId, ParserInternalError> = {
    <function:FunctionTerm> => function,
    <start:@L> <symbol:FunctionSymbol> <end:@R> => {
        context.new_node(AstKind::FunctionTerm, AstContent::None, vec![symbol?], start, end, None)
    }
}

pub Constraints: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":constraints" <con_gd:ConGD> ")" <end:@R> => {
        context.new_node(AstKind::Constraints, AstContent::None, vec![con_gd?], start, end, None)
    }
}

pub ConGD: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "and" <con_gd:ConGD*> ")" <end:@R> => {
        let con_gd = con_gd.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, con_gd, start, end, None)
    },
    <start:@L>
        "(" "forall"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")"
            <end_var:@R> <con_gd:ConGD>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Forall, AstContent::None, vec![variables?, con_gd?], start, end, None)
    },
    <start:@L> "(" "at end" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::AtEnd, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "always" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::Always, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "sometime" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::Sometime, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "within" <number:Number> <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::Within, AstContent::None, vec![number?, gd?], start, end, None)
    },
    <start:@L> "(" "at-most-once" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::AtMostOnce, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "sometime-after" <gd1:GD> <gd2:GD> ")" <end:@R> => {
        context.new_node(AstKind::SometimeAfter, AstContent::None, vec![gd1?, gd2?], start, end, None)
    },
    <start:@L> "(" "sometime-before" <gd1:GD> <gd2:GD> ")" <end:@R> => {
        context.new_node(AstKind::SometimeBefore, AstContent::None, vec![gd1?, gd2?], start, end, None)
    },
    <start:@L> "(" "always-within" <number:Number> <gd1:GD> <gd2:GD> ")" <end:@R> => {
        context.new_node(AstKind::AlwaysWithin, AstContent::None, vec![number?, gd1?, gd2?], start, end, None)
    },
    <start:@L> "(" "hold-during" <lower:Number> <upper:Number> <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::HoldDuring, AstContent::None, vec![lower?, upper?, gd?], start, end, None)
    },
    <start:@L> "(" "hold-after" <number:Number> <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::HoldAfter, AstContent::None, vec![number?, gd?], start, end, None)
    },
}

pub DerivedDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":derived" <atom:AtomicFormulaSkeleton> <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::DerivedDef, AstContent::None, vec![atom?, gd?], start, end, None)
    }
}

pub DurativeActionDef: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" ":durative-action" <name:DASymbol>
        <parameters:ParameterDef>
        <body:DADefBody>
    ")" <end:@R> => {
        context.new_node(AstKind::DurativeActionDef, AstContent::None, vec![name?, parameters?, body?], start, end, None)
    }
}

pub DADefBody: Result<NodeId, ParserInternalError> = {
    <start:@L>
        ":duration" <constraint:DurationConstraint>
        ":condition" <condition:EmptyOr<DAGD>>
        ":effect" <effect:EmptyAnd<DAEffect>>
    <end:@R> => {
        context.new_node(AstKind::DADefBody, AstContent::None, vec![constraint?, condition?, effect?], start, end, None)
    }
}

pub DurationConstraint: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "and" <constraints:SimpleDurationConstraint*> ")" <end:@R> => {
        let constraints = constraints.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, constraints, start, end, None)
    },
    <start:@L> "(" ")" <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, vec![], start, end, None)
    },
    <constraint:SimpleDurationConstraint> => constraint,
}

pub SimpleDurationConstraint: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <op:DOp> <var:DurationVariable> <value:DValue> ")" <end:@R> => {
        context.new_node(AstKind::FComp, op, vec![var?, value?], start, end, None)
    },
    <start:@L> "at start" <constraints:SimpleDurationConstraint> <end:@R> => {
        context.new_node(AstKind::AtStart, AstContent::None, vec![constraints?], start, end, None)
    },
    <start:@L> "at end" <constraints:SimpleDurationConstraint> <end:@R> => {
        context.new_node(AstKind::AtEnd, AstContent::None, vec![constraints?], start, end, None)
    },
}

pub DurationVariable: Result<NodeId, ParserInternalError> = {
    <start:@L> <var:"?duration"> <end:@R> => {
        context.new_node(AstKind::Variable, AstContent::Ident(context.intern(var.to_string())), vec![], start, end, None)
    }
}

pub DOp : AstContent = {
    ">=" =>AstContent::BinaryComp(BinaryComp::GreaterEq),
    "<=" =>AstContent::BinaryComp(BinaryComp::LessEq),
    "=" =>AstContent::BinaryComp(BinaryComp::Equal),
}

pub DValue: Result<NodeId, ParserInternalError> = {
    <fexp:FExp> => fexp,
}

pub DAGD: Result<NodeId, ParserInternalError> = {
    <pref_timed_gd:PrefTimedGD> => pref_timed_gd,
    <start:@L> "(" "and" <da_gd:DAGD*> ")" <end:@R> => {
        let da_gd = da_gd.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, da_gd, start, end, None)
    },
    <start:@L>
        "(" "forall"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <da_gd:DAGD>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Forall, AstContent::None, vec![variables?, da_gd?], start, end, None)
    },
}

pub PrefTimedGD: Result<NodeId, ParserInternalError> = {
    <timed_gd:TimedGD> => timed_gd,
    <start:@L> "(" "preference" <pref_name:PrefName?> <timed_gd:TimedGD> ")" <end:@R> => {
        let mut children = Vec::new();
        if let Some(pref_name) = pref_name {
            children.push(pref_name?);
        }
        children.push(timed_gd?);
        context.new_node(AstKind::Preference, AstContent::None, children, start, end, None)
    },
}

pub TimedGD: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "at start" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::AtStart, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "at end" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::AtEnd, AstContent::None, vec![gd?], start, end, None)
    },
    <start:@L> "(" "over all" <gd:GD> ")" <end:@R> => {
        context.new_node(AstKind::Overall, AstContent::None, vec![gd?], start, end, None)
    },
}

pub DAEffect: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "and" <da_effect:DAEffect*> ")" <end:@R> => {
        let da_effect = da_effect.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, da_effect, start, end, None)
    },
    <timed_effect:TimedEffect> => timed_effect,
    <start:@L>
        "(" "forall"
            <start_var:@L> "(" <variables:TypedList<Variable>> ")" <end_var:@R>
            <da_effect:DAEffect>
        ")"
    <end:@R> => {
        context.new_node(AstKind::Forall, AstContent::None, vec![variables?, da_effect?], start, end, None)
    },
    <start:@L> "(" "when" <da_gd:DAGD> <time_effect:TimedEffect> ")" <end:@R> => {
        context.new_node(AstKind::When, AstContent::None, vec![da_gd?, time_effect?], start, end, None)
    },
}

pub TimedEffect: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "at start" <con_effect:CondEffect> ")" <end:@R> => {
        context.new_node(AstKind::AtStart, AstContent::None, vec![con_effect?], start, end, None)
    },
    <start:@L> "(" "at end" <con_effect:CondEffect> ")" <end:@R> => {
        context.new_node(AstKind::AtEnd, AstContent::None, vec![con_effect?], start, end, None)
    },
    <start:@L> "(" <op:AssignOpT> <fhead:FHead> <fexpt:FExpT> ")" <end:@R> => {
        context.new_node(AstKind::Assign, op, vec![fhead?, fexpt?], start, end, None)
    },
}

pub FAssignDA: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <op:AssignOp> <fhead:FHead> <fexpda:FExpDA> ")" <end:@R> => {
        context.new_node(AstKind::Assign, op, vec![fhead?, fexpda?], start, end, None)
    },
}

pub AssignOpT : AstContent = {
    "increase" =>AstContent::AssignOp(AssignOp::Increase),
    "decrease" =>AstContent::AssignOp(AssignOp::Decrease),
}

pub FExpT: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "*" <fexp:FExp> <var:ContinusVariable> ")" <end:@R> => {
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Mul), vec![fexp?, var?], start, end, None)
    },
    <start:@L> "(" "*" <var:ContinusVariable> <fexp:FExp> ")" <end:@R> => {
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Mul), vec![var?, fexp?], start, end, None)
    },
    <var:ContinusVariable> => var,
}

pub ContinusVariable: Result<NodeId, ParserInternalError> = {
    <start:@L> <var:"#t"> <end:@R> => {
        context.new_node(AstKind::Variable, AstContent::Ident(context.intern(var.to_string())), Vec::new(), start, end, None)
    }
}

pub Domain: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" "define" "(" "domain" <name:DomainName> ")"
            <require_def:RequireDef?>
            <types_def:TypesDef?>
            <constants_def:ConstantsDef?>
            <predicates_def:PredicatesDef?>
            <functions_def:FunctionsDef?>
            <constraints:Constraints?>
            <structure_def:StructureDef*>
        ")"
    <end:@R> => {
        let mut children = Vec::new();
        children.push(name?);
        if let Some(require_def) = require_def {
            children.push(require_def?);
        }
        if let Some(types_def) = types_def {
            children.push(types_def?);
        }
        if let Some(constants_def) = constants_def {
            children.push(constants_def?);
        }
        if let Some(predicates_def) = predicates_def {
            children.push(predicates_def?);
        }
        if let Some(functions_def) = functions_def {
            children.push(functions_def?);
        }
        if let Some(constraints) = constraints {
            children.push(constraints?);
        }
        let structure_def = structure_def.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(structure_def);
        context.new_node(AstKind::Domain, AstContent::None, children, start, end, None)
    }
}

pub ObjectsDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":objects" <objects:TypedList<Constant>> ")" <end:@R> => {
        context.new_node(AstKind::ObjectsDef, AstContent::None, vec![objects?], start, end, None)
    }
}

pub BasicFunctionTerm : Result<NodeId, ParserInternalError> = {
    <function:FunctionTerm> => function,
    <symbol:FunctionSymbol> => symbol,
}

pub InitEl: Result<NodeId, ParserInternalError> = {
    <literal:Literal<Constant>> => literal,
    <start:@L> "(" <number:Number> <literal:Literal<Constant>> ")" <end:@R> => {
        context.new_node(AstKind::TimedInitialLiteral, AstContent::None, vec![number?, literal?], start, end, None)
    },
    <start:@L> "(" "=" <function:BasicFunctionTerm> <number:Number> ")" <end:@R> => {
        context.new_node(AstKind::FComp, AstContent::BinaryComp(BinaryComp::Equal), vec![function?, number?], start, end, None)
    },
    <start:@L> "(" "=" <function:BasicFunctionTerm> <constant:Constant> ")" <end:@R> => {
        context.new_node(AstKind::FComp, AstContent::BinaryComp(BinaryComp::Equal), vec![function?, constant?], start, end, None)
    },
}

pub Init: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":init" <init_els:InitEl*> ")" <end:@R> => {
        // Add and expression to uniformize
        let init_els = init_els.into_iter().collect::<Result<Vec<_>, _>>()?;
        let and_node = context.new_node(AstKind::And, AstContent::None, init_els, start, end, None);
        context.new_node(AstKind::Init, AstContent::None, vec![and_node?], start, end, None)
    },
}

pub Goal: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":goal" <pre_gd:PreGD> ")" <end:@R> => {
        let children = vec![pre_gd?];
        context.new_node(AstKind::Goal, AstContent::None, children, start, end, None)
    },
}

pub Optimization : AstContent = {
    "minimize" => AstContent::Optimization(Optimization::Minimize),
    "maximize" => AstContent::Optimization(Optimization::Maximize),
}

pub MetricFExp: Result<NodeId, ParserInternalError> = {
    <number:Number> => number,
    <function:_FunctionTerm<Constant>> => function,
    <start:@L> <symbol:FunctionSymbol> <end:@R> => {
        context.new_node(AstKind::FunctionTerm, AstContent::None, vec![symbol?], start, end, None)
    },
    <start:@L> "(" "-" <arg1:MetricFExp> <arg2:MetricFExp?> ")" <end:@R> => {
        let mut children = vec![arg1?];
        if let Some(arg2) = arg2 {
            children.push(arg2?);
        }
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Sub), children, start, end, None)
    },
    <start:@L> "(" "/" <arg1:MetricFExp> <arg2:MetricFExp> ")" <end:@R> => {
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Div), vec![arg1?, arg2?], start, end, None)
    },
    <start:@L> "(" "+" <arg1:MetricFExp> <next_args:MetricFExp+> ")" <end:@R> => {
        let mut children = vec![arg1?];
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Add), children, start, end, None)
    },
    <start:@L> "(" "*" <arg1:MetricFExp> <next_args:MetricFExp+> ")" <end:@R> => {
        let mut children = vec![arg1?];
        let next_args = next_args.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(next_args);
        context.new_node(AstKind::Operation, AstContent::ArithmeticOp(ArithmeticOp::Mul), children, start, end, None)
    },
    //<start:@L> "total-time" <end:@R> => {
    //    Context.new_node(AstKind::TotalTime, AstContent::None, Vec::new(), start, end, None)
    //}
    <start:@L> "(" "is-violated" <pref:PrefName> ")" <end:@R> => {
        context.new_node(AstKind::IsViolated, AstContent::None, vec![pref?], start, end, None)
    }
}

pub MetricSpec: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":metric" <op:Optimization> <fexp:MetricFExp> ")" <end:@R> => {
        context.new_node(AstKind::Metric, op, vec![fexp?], start, end, None)
    },
}

pub LengthSpec: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" ":length"
            <start_serial:@L> "(" ":serial" <serial_value:"number"?> ")" <end_serial:@R>
            <start_parallel:@L> "(" ":parallel" <parallel_value:"number"?> ")" <end_parallel:@R>
        ")"
    <end:@R> => {
        let mut children = Vec::new();
        if let Some(serial_value) = serial_value {
            let serial = context.new_node(AstKind::Serial, AstContent::Float(OrderedFloat(serial_value)), vec![], start_serial, end_serial, None);
            children.push(serial?);
        }
        if let Some(parallel_value) = parallel_value {
            let parallel = context.new_node(AstKind::Parallel, AstContent::Float(OrderedFloat(parallel_value)), vec![], start_parallel, end_parallel, None);
            children.push(parallel?);
        }
        context.new_node(AstKind::Length, AstContent::None, children, start, end, None)
    },
}

pub Problem: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" "define" "(" "problem" <problem:ProblemName> ")"
        "(" ":domain" <domain:DomainName> ")"
        <require_def:RequireDef?>
        <objects_def:ObjectsDef?>
        <init:Init>
        <goal:Goal>
        <constraints:Constraints?>
        <metric_spec:MetricSpec?>
        <length_spec:LengthSpec?>
        ")"
    <end:@R> => {
        let mut children = Vec::new();
        children.push(problem?);
        children.push(domain?);
        if let Some(require_def) = require_def {
            children.push(require_def?)
        }
        if let Some(objects_def) = objects_def {
            children.push(objects_def?)
        }
        children.push(init?);
        children.push(goal?);
        if let Some(constraints) = constraints {
            children.push(constraints?)
        }
        if let Some(metric_spec) = metric_spec {
            children.push(metric_spec?)
        }
        if let Some(length_spec) = length_spec {
            children.push(length_spec?)
        }
        context.new_node(AstKind::Problem, AstContent::None, children, start, end, None)
    },
}

pub PDDL: Result<NodeId, ParserInternalError> = {
    <domain:Domain> => domain,
    <problem:Problem> => problem,
}

///////////////////////////////////////////////////////////////////////////////////////////////
// HDDL Dialect
///////////////////////////////////////////////////////////////////////////////////////////////

pub TaskSymbol: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => {
        match name {
            Ok(name) => context.new_node(AstKind::TaskSymbol, name, Vec::new(), start, end, None),
            Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
        }
    },
}

pub TaskDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":task" <symbol:TaskSymbol> <parameters:ParameterDef> ")" <end:@R> => {
        context.new_node(AstKind::TaskDef, AstContent::None, vec![symbol?, parameters?], start, end, None)
    },
}

pub MethodSymbol: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => {
        match name {
            Ok(name) => context.new_node(AstKind::MethodSymbol, name, Vec::new(), start, end, None),
            Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
        }
    },
}

pub TaskID: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:Name> <end:@R> => match name {
        Ok(name) => context.new_node(AstKind::TaskID, name, Vec::new(), start, end, None),
        Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start, end, None),
    }
}

pub TaskTerm: Result<NodeId, ParserInternalError> = {
    <start:@L> <name:"id"> <end:@R> => {
        if !name.starts_with("?") {
            context.new_node(AstKind::Constant, AstContent::Ident(context.intern(name.to_string())), Vec::new(), start, end, None)
        } else {
            context.new_node(AstKind::Variable, AstContent::Ident(context.intern(name.to_string())), Vec::new(), start, end, None)
        }
    }
}

pub Task: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" <symbol:TaskSymbol> <terms:TaskTerm*> ")" <end:@R> => {
        let terms = terms.into_iter().collect::<Result<Vec<_>, _>>()?;
        let mut children = Vec::new();
        children.push(symbol?);
        children.extend(terms);
        context.new_node(AstKind::Task, AstContent::None, children, start, end, None)
    }
}

pub Subtask: Result<NodeId, ParserInternalError> = {
    "(" <start_name:@L> <name:Name> <end_name:@R> <rest:SubtaskRest> <end_rest:@R> => {
        let rest = rest?;
        match name {
            Ok(name_value) => {
                match rest.first().map(|node| context.arena().get_node(*node).unwrap().kind()) {
                    Some(AstKind::TaskSymbol) => {
                        let task_id = context.new_node(AstKind::TaskID, name_value, Vec::new(), start_name, end_name, None);
                        let task = context.new_node(AstKind::Task, AstContent::None, rest, end_name, end_rest, None);
                        context.new_node(AstKind::TaggedTask, AstContent::None, vec![task_id?, task?], start_name, end_rest, None)
                    },
                    Some(AstKind::Constant) | Some(AstKind::Variable) => {
                        let task_symbol = context.new_node(AstKind::TaskSymbol, name_value, Vec::new(), start_name, end_name, None);
                        let mut children = Vec::with_capacity(1 + rest.len());
                        children.push(task_symbol?);
                        children.extend(rest);
                        context.new_node(AstKind::Task, AstContent::None, children, start_name, end_rest, None)
                    },
                    None => {
                        let task_symbol = context.new_node(AstKind::TaskSymbol, name_value, Vec::new(), start_name, end_name, None);
                        context.new_node(AstKind::Task, AstContent::None, vec![task_symbol?], start_name, end_rest, None)
                    },
                    _ => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start_name, end_name, None)
                }
            },
            Err(_) => context.new_node(AstKind::Error, AstContent::None, Vec::new(), start_name, end_rest, None)
        }
    }
}

SubtaskRest: Result<Vec<NodeId>, ParserInternalError> = {
    <start:@L> "(" <task_symbol:TaskSymbol> <terms:TaskTerm*> ")" ")" <end:@R> => {
        let terms = terms.into_iter().collect::<Result<Vec<_>, _>>()?;
        let mut children = Vec::new();
        children.push(task_symbol?);
        children.extend(terms);
        Ok(children)
    },
    <start:@L> <terms:TaskTerm*> ")" <end:@R> => {
        let terms = terms.into_iter().collect::<Result<Vec<_>, _>>()?;
        Ok(terms)
    }
}
pub SubtaskDef: Result<NodeId, ParserInternalError> = {
    <start:@L> <subtask:Subtask> <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, vec![subtask?], start, end, None)
    },
    <start:@L> "(" ")" <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, vec![], start, end, None)
    },
    <start:@L> "(" "and" <subtasks:Subtask*> ")" <end:@R> => {
        let subtasks = subtasks.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, subtasks, start, end, None)
    }
}

pub TaskNetworkSubtaskDef: Result<NodeId, ParserInternalError> = {
    <start:@L> ":ordered-tasks" <subtasks:SubtaskDef> <end:@R> => {
        context.new_node(AstKind::OrderedSubtaskDef, AstContent::None, vec![subtasks?], start, end, None)
    },
    <start:@L> ":ordered-subtasks" <subtasks:SubtaskDef> <end:@R> => {
        context.new_node(AstKind::OrderedSubtaskDef, AstContent::None, vec![subtasks?], start, end, None)
    },
    <start:@L> ":tasks" <subtasks:SubtaskDef> <end:@R> => {
        context.new_node(AstKind::PartiallyOrderedSubtaskDef, AstContent::None, vec![subtasks?], start, end, None)
    },
    <start:@L> ":subtasks" <subtasks:SubtaskDef> <end:@R> => {
        context.new_node(AstKind::PartiallyOrderedSubtaskDef, AstContent::None, vec![subtasks?], start, end, None)
    }
}

pub SimpleTaskOrderingConstraint: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "<" <t1:TaskID> <t2:TaskID> ")" <end:@R> => {
        context.new_node(AstKind::TaskOrderingConstraint, AstContent::BinaryComp(BinaryComp::Less), vec![t1?, t2?], start, end, None)
    }
}

pub TaskOrderingConstraint: Result<NodeId, ParserInternalError> = {
    <start:@L> <constraint:SimpleTaskOrderingConstraint> <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, vec![constraint?], start, end, None)
    },
    <start:@L> "(" ")" <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, Vec::new(), start, end, None)
    },
    <start:@L> "(" "and" <constraints:SimpleTaskOrderingConstraint*> ")" <end:@R> => {
        let constraints = constraints.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, constraints, start, end, None)
    },
}

pub TaskNetworkOrderingConstraintDef: Result<NodeId, ParserInternalError> = {
    <start:@L> ":ordering" <constraints:TaskOrderingConstraint> <end:@R> => {
        context.new_node(AstKind::TaskOrderingConstraintDef, AstContent::None, vec![constraints?], start, end, None)
    },
    <start:@L> ":order" <constraints:TaskOrderingConstraint> <end:@R> => {
        context.new_node(AstKind::TaskOrderingConstraintDef, AstContent::None, vec![constraints?], start, end, None)
    },
}

pub SimpleTaskLogicalConstraint: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" "=" <t1:Term> <t2:Term> ")" <end:@R> => {
        context.new_node(AstKind::FComp, AstContent::BinaryComp(BinaryComp::Equal), vec![t1?, t2?], start, end, None)
    },
    <start:@L> "(" "not" <constraint:SimpleTaskLogicalConstraint> ")" <end:@R> => {
        context.new_node(AstKind::Not, AstContent::None, vec![constraint?], start, end, None)
    },
}

pub TaskLogicalConstraint: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ")" <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, Vec::new(), start, end, None)
    },
    <start:@L> <constraint:SimpleTaskLogicalConstraint> <end:@R> => {
        context.new_node(AstKind::And, AstContent::None, vec![constraint?], start, end, None)
    },
    <start:@L> "(" "and" <constraints:SimpleTaskLogicalConstraint*> ")" <end:@R> => {
        let constraints = constraints.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::And, AstContent::None, constraints, start, end, None)
    },
}

pub TaskNetworkLogicalConstraintDef: Result<NodeId, ParserInternalError> = {
    <start:@L> ":constraints" <constraint:TaskLogicalConstraint> <end:@R> => {
        context.new_node(AstKind::TaskLogicalConstraintDef, AstContent::None, vec![constraint?], start, end, None)
    },
}

pub TaskNetworkDef: Result<NodeId, ParserInternalError> = {
    <start:@L>
        <subtasks:TaskNetworkSubtaskDef?>
        <ordering_constraints:TaskNetworkOrderingConstraintDef?>
        <logical_constraints:TaskNetworkLogicalConstraintDef?>
    <end:@R> => {
        let mut children = Vec::new();
        if let Some(subtasks) = subtasks {
            children.push(subtasks?);
        }
        if let Some(ordering_constraints) = ordering_constraints {
            children.push(ordering_constraints?);
        }
        if let Some(logical_constraints) = logical_constraints {
            children.push(logical_constraints?);
        }
        context.new_node(AstKind::TaskNetworkDef, AstContent::None, children, start, end, None)
    },
}

pub MethodPreconditionDef: Result<NodeId, ParserInternalError> = {
    <start:@L> ":precondition" <gd:EmptyOr<GD>> <end:@R> => {
        context.new_node(AstKind::MethodPreconditionDef, AstContent::None, vec![gd?], start, end, None)
    },
}

pub MethodDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":method" <name:MethodSymbol> <parameters:ParameterDef> <body:MethodDefBody> ")" <end:@R> => {
        context.new_node(AstKind::MethodDef, AstContent::None, vec![name?, parameters?, body?], start, end, None)
    },
}

pub MethodDefBody: Result<NodeId, ParserInternalError> = {
    <start:@L>
        ":task" <task:Task>
        <precondition:MethodPreconditionDef?>
        <task_network:TaskNetworkDef>
    <end:@R> => {
        let mut children = vec![task?];
        if let Some(precondition) = precondition {
            children.push(precondition?);
        }
        children.push(task_network?);
        context.new_node(AstKind::MethodDefBody, AstContent::None, children, start, end, None)
    },
}

pub InitialTaskNetwork: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":htn" <parameters:ParameterDef?> <task_network:TaskNetworkDef> ")" <end:@R> => {
        let mut children = Vec::new();
        if let Some(parameters) = parameters {
            children.push(parameters?);
        }
        children.push(task_network?);
        context.new_node(AstKind::InitialTaskNetwork, AstContent::None, children, start, end, None)
    },
}

pub HDDLRequirement: Result<NodeId, ParserInternalError> = {
    <requirement:Requirement> => requirement,
    <start:@L> ":hierarchy" <end:@R> => {
        context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::Hierarchy), Vec::new(), start, end, None)
    },
    <start:@L> ":method-preconditions" <end:@R> => {
        context.new_node(AstKind::Requirement, AstContent::Requirement(Requirement::MethodPreconditions), Vec::new(), start, end, None)
    },
}

pub HDDLRequireDef: Result<NodeId, ParserInternalError> = {
    <start:@L> "(" ":requirements" <requirements:HDDLRequirement*> ")" <end:@R> => {
        let requirements = requirements.into_iter().collect::<Result<Vec<_>, _>>()?;
        context.new_node(AstKind::RequireDef, AstContent::None, requirements, start, end, None)
    },
}

pub HDDLStructureDef: Result<NodeId, ParserInternalError> = {
    <action:ActionDef> => action,
    <derived:DerivedDef> => derived,
    <durative_action:DurativeActionDef> => durative_action,
    <task:TaskDef> => task,
    <method:MethodDef> => method,
}

pub HDDLDomain: Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" "define" "(" "domain" <name:DomainName> ")"
            <require_def:HDDLRequireDef?>
            <types_def:TypesDef?>
            <constants_def:ConstantsDef?>
            <predicates_def:PredicatesDef?>
            <functions_def:FunctionsDef?>
            <structure_def:HDDLStructureDef*>
        ")"
    <end:@R> => {
        let mut children = Vec::new();
        children.push(name?);
        if let Some(require_def) = require_def {
            children.push(require_def?);
        }
        if let Some(types_def) = types_def {
            children.push(types_def?);
        }
        if let Some(constants_def) = constants_def {
            children.push(constants_def?);
        }
        if let Some(predicates_def) = predicates_def {
            children.push(predicates_def?);
        }
        if let Some(functions_def) = functions_def {
            children.push(functions_def?);
        }
        let structure_def = structure_def.into_iter().collect::<Result<Vec<_>, _>>()?;
        children.extend(structure_def);
        context.new_node(AstKind::Domain, AstContent::None, children, start, end, None)
    },
}

pub HDDLProblem : Result<NodeId, ParserInternalError> = {
    <start:@L>
        "(" "define" "(" "problem" <problem_name:ProblemName> ")"
        "(" ":domain" <domain_name:DomainName> ")"
        <require_def:HDDLRequireDef?>
        <objects_def:ObjectsDef?>
        <task_network:InitialTaskNetwork>
        <init:Init>
        <goal:Goal?>
        ")"
    <end:@R> => {
        let mut children = Vec::new();
        children.push(problem_name?);
        children.push(domain_name?);
        if let Some(require_def) = require_def {
           children.push(require_def?);
        }
        if let Some(objects_def) = objects_def {
           children.push(objects_def?);
        }
        children.push(task_network?);
        children.push(init?);
        if let Some(goal) = goal {
            children.push(goal?);
        }
        context.new_node(AstKind::Problem, AstContent::None, children, start, end, None)
    },
}

pub HDDL: Result<NodeId, ParserInternalError> = {
    <domain:HDDLDomain> => domain,
    <problem:HDDLProblem> => problem,
}
