use lalrpop_util::ParseError;
use crate::aiplan4rust::frontend::ParserInternalError;
use crate::aiplan4rust::syntax::{ParseContext, ParserError};
use crate::aiplan4rust::tree::{NodeId, TreeNode};
use crate::aiplan4rust::syntax::grammar::PDDLParser;
use crate::aiplan4rust::syntax::grammar::HDDLParser;
use crate::aiplan4rust::syntax::lexer::{Lexer, LexicalError, Token};

/// Parses a PDDL input using the provided lexer and updates the parsing context.
///
/// This function invokes the PDDL parser to process the token stream from the lexer.
/// If parsing succeeds and produces a root node, the root node ID is set in the context.
/// If parsing succeeds but results in an empty tree (no root), it returns `Ok(None)`.
/// If parsing fails, it returns a `ParseError`.
///
/// # Arguments
///
/// * `ctx` - Mutable reference to the parsing context, which holds the arena and other state.
/// * `lexer` - The lexer that provides the token stream for the parser.
///
/// # Returns
///
/// * `Ok(Some(root_id))` if parsing succeeds and a root node is found.
/// * `Ok(None)` if parsing succeeds but produces an empty tree (no root).
/// * `Err(ParseError)` if parsing fails.
///
/// # Errors
///
/// Returns any parsing error generated by the underlying parser.
///
/// # Examples
///
/// ```ignore
/// let mut ctx = ParseContext::new();
/// let lexer = Lexer::new(input);
/// let result = parse_pddl(&mut ctx, lexer)?;
///
/// match result {
///     Some(root_id) => println!("Parsed root node ID: {:?}", root_id),
///     None => println!("Parsed successfully but tree is empty."),
/// }
/// ```
pub fn parse_pddl(
    ctx: &mut ParseContext,
    lexer: Lexer,
) -> Result<NodeId, ParserError> {
    let parser = PDDLParser::new();

    // parser.parse retourne Result<Result<NodeId, ParserInternalError>, ParseError<...>>
    let inner_result = parser.parse(ctx, lexer)?; // <- ici ParseError est converti en ParserError via `From`

    let root_id = inner_result?; // <- ici ParserInternalError est converti en ParserError via `From`

    ctx.set_root_id(root_id)?;


    Ok(root_id)
}

/// Parses an HDDL input using the provided lexer and updates the parsing context.
///
/// This function invokes the HDDL parser to process the token stream from the lexer.
/// If parsing succeeds and produces a root node, the root node ID is set in the context.
/// If parsing succeeds but results in an empty tree (no root), it returns `Ok(None)`.
/// If parsing fails, it returns a `ParseError`.
///
/// # Arguments
///
/// * `ctx` - Mutable reference to the parsing context, which holds the arena and other state.
/// * `lexer` - The lexer that provides the token stream for the parser.
///
/// # Returns
///
/// * `Ok(Some(root_id))` if parsing succeeds and a root node is found.
/// * `Ok(None)` if parsing succeeds but produces an empty tree (no root).
/// * `Err(ParseError)` if parsing fails.
///
/// # Errors
///
/// Returns any parsing error generated by the underlying parser.
///
/// # Examples
///
/// ```ignore
/// let mut ctx = ParseContext::new();
/// let lexer = Lexer::new(input);
/// let result = parse_hddl(&mut ctx, lexer)?;
///
/// match result {
///     Some(root_id) => println!("Parsed root node ID: {:?}", root_id),
///     None => println!("Parsed successfully but tree is empty."),
/// }
/// ```
pub fn parse_hddl(
    ctx: &mut ParseContext,
    lexer: Lexer,
) -> Result<NodeId, ParserError> {

    let parser = HDDLParser::new();

    // parser.parse retourne Result<Result<NodeId, ParserInternalError>, ParseError<...>>
    let inner_result = parser.parse(ctx, lexer)?; // <- ici ParseError est converti en ParserError via `From`

    let root_id = inner_result?; // <- ici ParserInternalError est converti en ParserError via `From`

    ctx.set_root_id(root_id)?;


    Ok(root_id)
}

//Result<Result<NodeId, ParserInternalError>, ParseError<usize, Token, LexicalError>>
