///! # Parser Error Handling Module
///
/// This module defines the `ParserError` enum, which represents all errors
/// that can occur during parsing in the `aiplan4rust` project.
///
/// It covers two main categories of errors:
/// - **Parse errors**: Syntax and lexical errors generated by the LALRPOP parser
///   when processing the input source code.
/// - **Internal parser errors**: Unexpected or internal failures within the parser logic.
///
/// The `ParserError` enum implements the standard `std::error::Error` and
/// `std::fmt::Display` traits to provide descriptive error messages and
/// support error chaining.
///
/// Conversion implementations (`From`) are provided to easily convert
/// from lower-level error types (`lalrpop_util::ParseError` and
/// `ParserInternalError`) into `ParserError`, allowing use of the `?` operator
/// for ergonomic error handling.
///
/// This module is essential for robust error reporting and management
/// during the parsing phase of the AI planning language processing pipeline.
///

use std::fmt;
use std::error::Error;

use lalrpop_util::ParseError;
use crate::aiplan4rust::syntax::lexer::{LexicalError, Token};
use crate::aiplan4rust::AiplanError;

/// Represents errors that can occur during parsing.
///
/// This enum encapsulates two kinds of errors:
/// - `ParseError`: Errors produced by the parsing process, typically syntax errors
///   reported by the LALRPOP parser.
/// - `InternalError`: Internal errors encountered within the parser itself,
///   represented by `ParserInternalError`.
#[derive(Debug)]
pub enum ParserError {
    /// Parsing error reported by LALRPOP parser.
    ParseError(ParseError<usize, Token, LexicalError>),

    /// Internal parser error.
    InternalError(AiplanError),
}

impl fmt::Display for ParserError {
    /// Formats the `ParserError` for user-friendly display.
    ///
    /// Distinguishes between parse errors and internal errors with different messages.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ParserError::ParseError(e) => write!(f, "Parse error: {}", e),
            ParserError::InternalError(e) => write!(f, "Internal parser error: {}", e),
        }
    }
}

impl Error for ParserError {
    /// Returns the underlying source error, if any.
    ///
    /// This allows error chaining for better diagnostics.
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ParserError::ParseError(e) => Some(e),
            ParserError::InternalError(e) => Some(e),
        }
    }
}

/// Enables automatic conversion from `lalrpop_util::ParseError` to `ParserError`.
///
/// This allows using the `?` operator conveniently on parse errors.
impl From<ParseError<usize, Token, LexicalError>> for ParserError {
    fn from(e: ParseError<usize, Token, LexicalError>) -> Self {
        ParserError::ParseError(e)
    }
}

/// Enables automatic conversion from `ParserInternalError` to `ParserError`.
///
/// This allows using the `?` operator conveniently on internal parser errors.
impl From<AiplanError> for ParserError {
    fn from(e: AiplanError) -> Self {
        ParserError::InternalError(e)
    }
}
