name: Security Audit

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Bonus : scanne automatiquement tous les lundis à minuit

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run security audit
        uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ github.token }}
