//! This module defines the `Artefact` enum, representing outputs
//! generated by the planning system pipeline.
//!
//! An `Artefact` can either be **raw content** directly from input files
//! or **intermediate representation (IR) content** processed by the system.
//!
//! # Structure
//!
//! The `Artefact` enum has two variants:
//! - `Raw`: Represents raw input content along with its file path.
//! - `IR`: Represents intermediate representation content along with its file path.
//!
//! Each variant contains the following fields:
//!
//! ## `Raw`
//! - `path: PathBuf` — The path where the raw output is or will be stored.
//! - `content: RawContent` — The raw content associated with this artefact.
//!
//! ## `IR`
//! - `path: PathBuf` — The path where the IR output is or will be stored.
//! - `content: IRContent` — The intermediate representation content.
//!
//! # Example
//!
//! ```rust
//! use std::path::PathBuf;
//! use crate::aiplan4rust::artefact::{Artefact, RawContent, IRContent};
//!
//! // Example of a raw artefact
//! let raw_content = RawContent::new(...); // create or load RawContent
//! let raw_artefact = Artefact::Raw {
//!     path: PathBuf::from("domain.pddl"),
//!     content: raw_content,
//! };
//!
//! // Example of an IR artefact
//! let ir_content = IRContent::new(...); // create or load IRContent
//! let ir_artefact = Artefact::IR {
//!     path: PathBuf::from("domain.lift"),
//!     content: ir_content,
//! };
//! ```

use std::fs;
use std::path::{Path, PathBuf};
use std::fmt;

use crate::aiplan4rust::artefact::error::ArtefactError;
use crate::aiplan4rust::artefact::ir::header::{Header, HEADER_PAYLOAD_SEPARATOR};
use crate::aiplan4rust::artefact::ir::content::IRContent;
use crate::aiplan4rust::artefact::raw::content::RawContent;

/// Represents an output artefact in the planning pipeline.
///
/// Artefacts can be either **raw outputs** from input files or
/// **intermediate representation (IR) outputs** produced during processing.
#[derive(Debug)]
pub enum Artefact {
    /// Raw output content.
    ///
    /// Contains:
    /// - `path`: Path to the raw output file.
    /// - `content`: The raw content itself.
    Raw {
        path: PathBuf,
        content: RawContent,
    },

    /// Intermediate representation (IR) output.
    ///
    /// Contains:
    /// - `path`: Path to the IR output file.
    /// - `content`: The IR content.
    IR {
        path: PathBuf,
        content: IRContent,
    },
}

impl Artefact {
    /// Creates a new `Raw` artefact with the given path and raw content.
    ///
    /// # Example
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use crate::aiplan4rust::artefact::{Artefact, RawContent};
    ///
    /// let raw_content = RawContent::new(...);
    /// let artefact = Artefact::new_raw(PathBuf::from("domain.pddl"), raw_content);
    /// ```
    pub fn new_raw(path: PathBuf, content: RawContent) -> Self {
        Artefact::Raw { path, content }
    }

    /// Creates a new `IR` artefact with the given path and IR content.
    ///
    /// # Example
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use crate::aiplan4rust::artefact::{Artefact, IRContent};
    ///
    /// let ir_content = IRContent::new(...);
    /// let artefact = Artefact::new_ir(PathBuf::from("domain.lift"), ir_content);
    /// ```
    pub fn new_ir(path: PathBuf, content: IRContent) -> Self {
        Artefact::IR { path, content }
    }

    /// Returns the path associated with this artefact.
    ///
    /// Works for both `Raw` and `IR` variants.
    ///
    /// # Example
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use crate::aiplan4rust::artefact::{Artefact, IRContent};
    ///
    /// let ir_content = IRContent::new(...);
    /// let artefact = Artefact::new_ir(PathBuf::from("domain.lift"), ir_content);
    /// assert_eq!(artefact.path(), PathBuf::from("domain.lift"));
    /// ```
    pub fn path(&self) -> &Path {
        match self {
            Artefact::Raw { path, .. } => path,
            Artefact::IR { path, .. } => path,
        }
    }

    // --- RawContent ---

    /// Returns a reference to the raw content if this artefact is `Raw`.
    ///
    /// # Example
    ///
    /// ```rust
    /// use crate::aiplan4rust::artefact::{Artefact, RawContent};
    ///
    /// let raw_content = RawContent::new(...);
    /// let artefact = Artefact::new_raw("domain.pddl".into(), raw_content);
    ///
    /// if let Some(content) = artefact.raw_content() {
    ///     // Do something with the raw content
    /// }
    /// ```
    pub fn raw_content(&self) -> Option<&RawContent> {
        match self {
            Artefact::Raw { content, .. } => Some(content),
            _ => None,
        }
    }

    /// Returns a reference to the raw content if this artefact is `Raw`,
    /// or an error if not.
    ///
    /// # Errors
    ///
    /// Returns `ArtefactError::missing_raw_content()` if the artefact is not `Raw`.
    ///
    /// # Example
    ///
    /// ```rust
    /// use crate::aiplan4rust::artefact::{Artefact, RawContent};
    ///
    /// let raw_content = RawContent::new(...);
    /// let artefact = Artefact::new_raw("domain.pddl".into(), raw_content);
    ///
    /// let content = artefact.try_raw_content().unwrap();
    /// ```
    pub fn try_raw_content(&self) -> Result<&RawContent, ArtefactError> {
        match self {
            Artefact::Raw { content, .. } => Ok(content),
            _ => Err(ArtefactError::missing_raw_content()),
        }
    }

    /// Returns a reference to the IR content if this artefact is `IR`.
    ///
    /// # Example
    ///
    /// ```rust
    /// use crate::aiplan4rust::artefact::{Artefact, IRContent};
    ///
    /// let ir_content = IRContent::new(...);
    /// let artefact = Artefact::new_ir("domain.lift".into(), ir_content);
    ///
    /// if let Some(content) = artefact.ir_content() {
    ///     // Do something with the IR content
    /// }
    /// ```
    pub fn ir_content(&self) -> Option<&IRContent> {
        match self {
            Artefact::IR { content, .. } => Some(content),
            _ => None,
        }
    }

    /// Returns a reference to the IR content if this artefact is `IR`,
    /// or an error if not.
    ///
    /// # Errors
    ///
    /// Returns `ArtefactError::missing_ir_content()` if the artefact is not `IR`.
    ///
    /// # Example
    ///
    /// ```rust
    /// use crate::aiplan4rust::artefact::{Artefact, IRContent};
    ///
    /// let ir_content = IRContent::new(...);
    /// let artefact = Artefact::new_ir("domain.lift".into(), ir_content);
    ///
    /// let content = artefact.try_ir_content().unwrap();
    /// ```
    pub fn try_ir_content(&self) -> Result<&IRContent, ArtefactError> {
        match self {
            Artefact::IR { content, .. } => Ok(content),
            _ => Err(ArtefactError::missing_ir_content()),
        }
    }

    /// Writes the `Artefact` to its associated file path on disk.
    ///
    /// This method handles both variants of `Artefact`:
    ///
    /// - **Raw**: writes the raw content bytes directly to the file.
    /// - **IR**: serializes the intermediate representation with a header,
    ///   a separator, and the payload bytes, then writes the resulting bytes.
    ///
    /// # Errors
    ///
    /// Returns an `ArtefactError` if:
    /// - Writing to the file fails (e.g., due to permission issues or invalid path).
    /// - Serializing an IR artefact fails.
    ///
    /// # Example
    ///
    /// ```rust
    /// use std::path::PathBuf;
    /// use crate::aiplan4rust::artefact::{Artefact, RawContent, IRContent, Extension};
    ///
    /// // Example: writing a raw artefact
    /// let raw_content = RawContent::new(...);
    /// let raw_path = PathBuf::from("domain.pddl");
    /// let raw_artefact = Artefact::Raw {
    ///     path: raw_path.clone(),
    ///     content: raw_content,
    /// };
    /// raw_artefact.write().unwrap();
    ///
    /// // Example: writing an IR artefact
    /// let ir_content = IRContent::new(...);
    /// let ir_path = PathBuf::from("domain.lift");
    /// let ir_artefact = Artefact::IR {
    ///     path: ir_path.clone(),
    ///     content: ir_content,
    /// };
    /// ir_artefact.write().unwrap();
    /// ```
    pub fn write(&self) -> Result<(), ArtefactError> {
        match self {
            Artefact::Raw { content, .. } => fs::write(self.path(), content.inner())?,
            Artefact::IR { content, .. } => {
                let bytes = Self::serialize_with_header(content)?;
                fs::write(self.path(), bytes)?
            }
        }
        Ok(())
    }

    /// Serializes an `IRContent` into a byte vector with a JSON header.
    ///
    /// This function generates a structured output consisting of:
    /// 1. A JSON header containing the content's format, version, and kind.
    /// 2. A separator string (`HEADER_PAYLOAD_SEPARATOR`).
    /// 3. The serialized payload bytes.
    ///
    /// The resulting vector can be used for storing or transmitting IR content
    /// in a self-describing format.
    ///
    /// # Arguments
    ///
    /// * `content` - The `IRContent` to serialize.
    ///
    /// # Returns
    ///
    /// A `Result<Vec<u8>, ArtefactError>` containing the concatenated bytes of
    /// the header, separator, and payload, or an error if serialization fails.
    ///
    /// # Errors
    ///
    /// Returns `ArtefactError` if:
    /// - JSON serialization of the header fails,
    /// - or payload serialization to bytes fails.
    ///
    /// # Example
    ///
    /// ```rust
    /// use crate::aiplan4rust::artefact::{serialize_with_header, IRContent};
    ///
    /// // Suppose `ir_content` is an instance of IRContent
    /// let ir_content: IRContent = ...;
    ///
    /// let bytes = serialize_with_header(&ir_content).unwrap();
    /// assert!(!bytes.is_empty());
    /// ```
    fn serialize_with_header(
        content: &IRContent,
    ) -> Result<Vec<u8>, ArtefactError> {
        // Create the header
        let format = content.format();
        let header = Header::new(format, 1, content.kind());

        // Serialize header to JSON
        let header_str = serde_json::to_string_pretty(&header)?;

        // Serialize payload to bytes according to format
        let payload = content.serialize_to_bytes()?; // Returns Vec<u8>

        // Concatenate header + separator + payload
        let mut result = Vec::with_capacity(
            header_str.len() + HEADER_PAYLOAD_SEPARATOR.len() + payload.len()
        );
        result.extend_from_slice(header_str.as_bytes());
        result.extend_from_slice(HEADER_PAYLOAD_SEPARATOR.as_bytes());
        result.extend_from_slice(&payload);

        Ok(result)
    }

}

/// Implements `Display` for `Artefact` to provide a human-readable
/// representation of the output artefact.
///
/// This implementation distinguishes between **raw outputs** and
/// **intermediate representation (IR) outputs**, and formats
/// their key fields for easy debugging or logging.
///
/// # Example
///
/// ```rust
/// use std::path::PathBuf;
/// use crate::aiplan4rust::artefact::{Artefact, RawContent, IRContent};
///
/// // Example for a raw output
/// let raw_content = RawContent::new(...); // create your RawContent
/// let raw_artefact = Artefact::Raw {
///     path: PathBuf::from("domain.pddl"),
///     content: raw_content,
/// };
/// println!("{}", raw_artefact);
///
/// // Example for an IR output
/// let ir_content = IRContent::new(...); // create your IRContent
/// let ir_artefact = Artefact::IR {
///     path: PathBuf::from("domain.lift"),
///     content: ir_content,
/// };
/// println!("{}", ir_artefact);
/// ```
impl fmt::Display for Artefact {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Artefact::Raw { path, content } => {
                write!(
                    f,
                    "Raw Output {{ kind: {}, path: {}, language: {}, length: {} }}",
                    content.kind(),
                    path.display(),
                    content.language(),
                    content.inner().len()
                )
            }
            Artefact::IR { path, content } => {
                write!(
                    f,
                    "IR Output {{ kind: {}, path: {}, format: {} }}",
                    content.kind(),
                    path.display(),
                    content.format()
                )
            }
        }
    }
}
